source 'http://rubygems.org'

gem 'rails', '~> 3.1'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

# database
gem 'sqlite3-ruby', :require => 'sqlite3'
gem 'mysql2'

# Rails 3.1 - Asset Pipeline
gem 'json'
gem 'sass'
gem 'coffee-script'
gem 'uglifier'
gem 'therubyracer', :require => 'v8'

# Rails 3.1 - jQuery support
gem 'jquery-rails'

# application-specific gems
gem 'devise', '~> 1.4.7'
gem 'cancan', '~> 1.6.7'
gem 'paperclip', '~> 2.4.3'
gem 'exifr', '~> 1.1.1'
gem 'kaminari', '~> 0.12.4'
gem 'acts-as-taggable-on', '~> 2.1.0'
gem 'acts_as_commentable', '~> 3.0.1'

gem 'fancybox-rails'

# Use unicorn as the web server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger
# gem 'ruby-debug'

# Bundle the extra gems:
# gem 'bj'
# gem 'nokogiri'
# gem 'sqlite3-ruby', :require => 'sqlite3'
# gem 'aws-s3', :require => 'aws/s3'

# Bundle gems for the local environment. Make sure to
# put test-only gems in this group so their generators
# and rake tasks are available in development mode:
# group :development, :test do
#   gem 'webrat'
# end
